// After making changes to the *.proto files, always run the following
// command in current directory to update the generated code:
// go generate

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rollout.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Result is the result of the plugin response.
type RolloutPluginResponse_Result int32

const (
	RolloutPluginResponse_RESULT_UNSPECIFIED RolloutPluginResponse_Result = 0
	// OK is the ok response.
	RolloutPluginResponse_OK RolloutPluginResponse_Result = 1
	// FAILED is the failed response.
	RolloutPluginResponse_FAILED RolloutPluginResponse_Result = 2
)

// Enum value maps for RolloutPluginResponse_Result.
var (
	RolloutPluginResponse_Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "OK",
		2: "FAILED",
	}
	RolloutPluginResponse_Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"OK":                 1,
		"FAILED":             2,
	}
)

func (x RolloutPluginResponse_Result) Enum() *RolloutPluginResponse_Result {
	p := new(RolloutPluginResponse_Result)
	*p = x
	return p
}

func (x RolloutPluginResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutPluginResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[0].Descriptor()
}

func (RolloutPluginResponse_Result) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[0]
}

func (x RolloutPluginResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutPluginResponse_Result.Descriptor instead.
func (RolloutPluginResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{6, 0}
}

// Result is the result of the validation response.
type ValidateResponse_Result int32

const (
	// RESULT_UNSPECIFIED is the unspecified result.
	ValidateResponse_RESULT_UNSPECIFIED ValidateResponse_Result = 0
	// SUCCEEDED represents the successful result of the validation.
	// MWRS Controller continues the rollout to the next group of clusters.
	ValidateResponse_SUCCEEDED ValidateResponse_Result = 1
	// FAILED represents the failed result of the validation.
	// MWRS Controller stops the current rollout and rollback is triggered if the rollback is required.
	ValidateResponse_FAILED ValidateResponse_Result = 2
	// INPROGRESS represents the state where the validation is still in progress.
	// MWRS Controller keeps calling this method until the result is not INPROGRESS.
	ValidateResponse_INPROGRESS ValidateResponse_Result = 3
)

// Enum value maps for ValidateResponse_Result.
var (
	ValidateResponse_Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "SUCCEEDED",
		2: "FAILED",
		3: "INPROGRESS",
	}
	ValidateResponse_Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"SUCCEEDED":          1,
		"FAILED":             2,
		"INPROGRESS":         3,
	}
)

func (x ValidateResponse_Result) Enum() *ValidateResponse_Result {
	p := new(ValidateResponse_Result)
	*p = x
	return p
}

func (x ValidateResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[1].Descriptor()
}

func (ValidateResponse_Result) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[1]
}

func (x ValidateResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateResponse_Result.Descriptor instead.
func (ValidateResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{7, 0}
}

type MutateManifestWorkRequest_RolloutState int32

const (
	MutateManifestWorkRequest_ROLLOUT_STATE_UNSPECIFIED MutateManifestWorkRequest_RolloutState = 0
	// ROLLOUT is the rollout state for the rollout.
	MutateManifestWorkRequest_ROLLOUT MutateManifestWorkRequest_RolloutState = 1
	// ROLLBACK is the rollout state for the rollback.
	MutateManifestWorkRequest_ROLLBACK MutateManifestWorkRequest_RolloutState = 2
)

// Enum value maps for MutateManifestWorkRequest_RolloutState.
var (
	MutateManifestWorkRequest_RolloutState_name = map[int32]string{
		0: "ROLLOUT_STATE_UNSPECIFIED",
		1: "ROLLOUT",
		2: "ROLLBACK",
	}
	MutateManifestWorkRequest_RolloutState_value = map[string]int32{
		"ROLLOUT_STATE_UNSPECIFIED": 0,
		"ROLLOUT":                   1,
		"ROLLBACK":                  2,
	}
)

func (x MutateManifestWorkRequest_RolloutState) Enum() *MutateManifestWorkRequest_RolloutState {
	p := new(MutateManifestWorkRequest_RolloutState)
	*p = x
	return p
}

func (x MutateManifestWorkRequest_RolloutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutateManifestWorkRequest_RolloutState) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[2].Descriptor()
}

func (MutateManifestWorkRequest_RolloutState) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[2]
}

func (x MutateManifestWorkRequest_RolloutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutateManifestWorkRequest_RolloutState.Descriptor instead.
func (MutateManifestWorkRequest_RolloutState) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{8, 0}
}

// InitializeRequest is the request to initialize the plugin.
type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ocm_version is the version of the OCM API.
	OcmVersion    string `protobuf:"bytes,1,opt,name=ocm_version,json=ocmVersion,proto3" json:"ocm_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_rollout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetOcmVersion() string {
	if x != nil {
		return x.OcmVersion
	}
	return ""
}

// InitializeResponse is the response from the plugin after initialization.
// The plugin returns the name, version, and capabilities of the plugin.
type InitializeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the plugin.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// capabilities is the capabilities of the plugin.
	Capabilities  *InitializeResponse_Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_rollout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitializeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitializeResponse) GetCapabilities() *InitializeResponse_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ClusterRolloutStatus is the status of the cluster rollout.
type ClusterRolloutStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rollout_status is the status of the cluster rollout.
	RolloutStatus string `protobuf:"bytes,2,opt,name=rollout_status,json=rolloutStatus,proto3" json:"rollout_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRolloutStatus) Reset() {
	*x = ClusterRolloutStatus{}
	mi := &file_rollout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRolloutStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRolloutStatus) ProtoMessage() {}

func (x *ClusterRolloutStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRolloutStatus.ProtoReflect.Descriptor instead.
func (*ClusterRolloutStatus) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterRolloutStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterRolloutStatus) GetRolloutStatus() string {
	if x != nil {
		return x.RolloutStatus
	}
	return ""
}

// RolloutDetails is the details of the rollout.
type RolloutDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// completed is the clusters that have been completed.
	Completed []*ClusterRolloutStatus `protobuf:"bytes,1,rep,name=completed,proto3" json:"completed,omitempty"`
	// in_progress is the clusters that are currently being rolled out.
	InProgress []*ClusterRolloutStatus `protobuf:"bytes,2,rep,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	// timed_out is the clusters that have timed out.
	TimedOut []*ClusterRolloutStatus `protobuf:"bytes,3,rep,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// removed is the clusters that have been removed.
	Removed []*ClusterRolloutStatus `protobuf:"bytes,4,rep,name=removed,proto3" json:"removed,omitempty"`
	// placement_total_clusters is the total clusters in placement decision.
	PlacementTotalClusters int32 `protobuf:"varint,6,opt,name=placement_total_clusters,json=placementTotalClusters,proto3" json:"placement_total_clusters,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RolloutDetails) Reset() {
	*x = RolloutDetails{}
	mi := &file_rollout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutDetails) ProtoMessage() {}

func (x *RolloutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutDetails.ProtoReflect.Descriptor instead.
func (*RolloutDetails) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{3}
}

func (x *RolloutDetails) GetCompleted() []*ClusterRolloutStatus {
	if x != nil {
		return x.Completed
	}
	return nil
}

func (x *RolloutDetails) GetInProgress() []*ClusterRolloutStatus {
	if x != nil {
		return x.InProgress
	}
	return nil
}

func (x *RolloutDetails) GetTimedOut() []*ClusterRolloutStatus {
	if x != nil {
		return x.TimedOut
	}
	return nil
}

func (x *RolloutDetails) GetRemoved() []*ClusterRolloutStatus {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *RolloutDetails) GetPlacementTotalClusters() int32 {
	if x != nil {
		return x.PlacementTotalClusters
	}
	return 0
}

// RolloutMeta is the metadata of the rollout.
type RolloutMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mwrs_name is the name of the manifestwork resource set.
	MwrsName string `protobuf:"bytes,1,opt,name=mwrs_name,json=mwrsName,proto3" json:"mwrs_name,omitempty"`
	// placement_name is the name of the placement.
	PlacementName string `protobuf:"bytes,2,opt,name=placement_name,json=placementName,proto3" json:"placement_name,omitempty"`
	// namespace is the namespace where mwrs and placement are located.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// cluster_name is the name of the cluster.
	ClusterName   *string `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3,oneof" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutMeta) Reset() {
	*x = RolloutMeta{}
	mi := &file_rollout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutMeta) ProtoMessage() {}

func (x *RolloutMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutMeta.ProtoReflect.Descriptor instead.
func (*RolloutMeta) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{4}
}

func (x *RolloutMeta) GetMwrsName() string {
	if x != nil {
		return x.MwrsName
	}
	return ""
}

func (x *RolloutMeta) GetPlacementName() string {
	if x != nil {
		return x.PlacementName
	}
	return ""
}

func (x *RolloutMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RolloutMeta) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

// RolloutPluginRequest is the request to the rollout plugin.
type RolloutPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata is the metadata of the rollout.
	Metadata *RolloutMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// rollout_details is the details of the rollout.
	RolloutDetails *RolloutDetails `protobuf:"bytes,7,opt,name=rollout_details,json=rolloutDetails,proto3,oneof" json:"rollout_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RolloutPluginRequest) Reset() {
	*x = RolloutPluginRequest{}
	mi := &file_rollout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPluginRequest) ProtoMessage() {}

func (x *RolloutPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPluginRequest.ProtoReflect.Descriptor instead.
func (*RolloutPluginRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{5}
}

func (x *RolloutPluginRequest) GetMetadata() *RolloutMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RolloutPluginRequest) GetRolloutDetails() *RolloutDetails {
	if x != nil {
		return x.RolloutDetails
	}
	return nil
}

// RolloutPluginResponse is the response from the plugin.
type RolloutPluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the result of the response.
	Result RolloutPluginResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse_Result" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*RolloutPluginResponse_TextData
	//	*RolloutPluginResponse_ProtoData
	Data          isRolloutPluginResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutPluginResponse) Reset() {
	*x = RolloutPluginResponse{}
	mi := &file_rollout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPluginResponse) ProtoMessage() {}

func (x *RolloutPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPluginResponse.ProtoReflect.Descriptor instead.
func (*RolloutPluginResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{6}
}

func (x *RolloutPluginResponse) GetResult() RolloutPluginResponse_Result {
	if x != nil {
		return x.Result
	}
	return RolloutPluginResponse_RESULT_UNSPECIFIED
}

func (x *RolloutPluginResponse) GetData() isRolloutPluginResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RolloutPluginResponse) GetTextData() string {
	if x != nil {
		if x, ok := x.Data.(*RolloutPluginResponse_TextData); ok {
			return x.TextData
		}
	}
	return ""
}

func (x *RolloutPluginResponse) GetProtoData() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*RolloutPluginResponse_ProtoData); ok {
			return x.ProtoData
		}
	}
	return nil
}

type isRolloutPluginResponse_Data interface {
	isRolloutPluginResponse_Data()
}

type RolloutPluginResponse_TextData struct {
	// text_data is the text data of the response.
	TextData string `protobuf:"bytes,2,opt,name=text_data,json=textData,proto3,oneof"`
}

type RolloutPluginResponse_ProtoData struct {
	// proto_data is the protobuf data of the response.
	ProtoData *anypb.Any `protobuf:"bytes,3,opt,name=proto_data,json=protoData,proto3,oneof"`
}

func (*RolloutPluginResponse_TextData) isRolloutPluginResponse_Data() {}

func (*RolloutPluginResponse_ProtoData) isRolloutPluginResponse_Data() {}

// ValidateResponse is the response from the plugin for the validation of the rollout.
type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the result of the response.
	Result ValidateResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse_Result" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ValidateResponse_TextData
	//	*ValidateResponse_ProtoData
	Data          isValidateResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_rollout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateResponse) GetResult() ValidateResponse_Result {
	if x != nil {
		return x.Result
	}
	return ValidateResponse_RESULT_UNSPECIFIED
}

func (x *ValidateResponse) GetData() isValidateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ValidateResponse) GetTextData() string {
	if x != nil {
		if x, ok := x.Data.(*ValidateResponse_TextData); ok {
			return x.TextData
		}
	}
	return ""
}

func (x *ValidateResponse) GetProtoData() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*ValidateResponse_ProtoData); ok {
			return x.ProtoData
		}
	}
	return nil
}

type isValidateResponse_Data interface {
	isValidateResponse_Data()
}

type ValidateResponse_TextData struct {
	// text_data is the text data of the response.
	TextData string `protobuf:"bytes,2,opt,name=text_data,json=textData,proto3,oneof"`
}

type ValidateResponse_ProtoData struct {
	// proto_data is the protobuf data of the response.
	ProtoData *anypb.Any `protobuf:"bytes,3,opt,name=proto_data,json=protoData,proto3,oneof"`
}

func (*ValidateResponse_TextData) isValidateResponse_Data() {}

func (*ValidateResponse_ProtoData) isValidateResponse_Data() {}

// MutateManifestWorkRequest is the request to mutate the manifestwork resource before it is applied.
type MutateManifestWorkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rollout_state is the rollout state.
	RolloutState MutateManifestWorkRequest_RolloutState `protobuf:"varint,1,opt,name=rollout_state,json=rolloutState,proto3,enum=io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest_RolloutState" json:"rollout_state,omitempty"`
	// metadata is the metadata of the rollout.
	Metadata *RolloutMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// rollout_details is the details of the rollout.
	RolloutDetails *RolloutDetails `protobuf:"bytes,3,opt,name=rollout_details,json=rolloutDetails,proto3,oneof" json:"rollout_details,omitempty"`
	// manifestwork is the unstructured manifestwork resource.
	Manifestwork  *runtime.Unknown `protobuf:"bytes,4,opt,name=manifestwork,proto3" json:"manifestwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateManifestWorkRequest) Reset() {
	*x = MutateManifestWorkRequest{}
	mi := &file_rollout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateManifestWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateManifestWorkRequest) ProtoMessage() {}

func (x *MutateManifestWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateManifestWorkRequest.ProtoReflect.Descriptor instead.
func (*MutateManifestWorkRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{8}
}

func (x *MutateManifestWorkRequest) GetRolloutState() MutateManifestWorkRequest_RolloutState {
	if x != nil {
		return x.RolloutState
	}
	return MutateManifestWorkRequest_ROLLOUT_STATE_UNSPECIFIED
}

func (x *MutateManifestWorkRequest) GetMetadata() *RolloutMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MutateManifestWorkRequest) GetRolloutDetails() *RolloutDetails {
	if x != nil {
		return x.RolloutDetails
	}
	return nil
}

func (x *MutateManifestWorkRequest) GetManifestwork() *runtime.Unknown {
	if x != nil {
		return x.Manifestwork
	}
	return nil
}

// MutateManifestWorkResponse is the response to mutate the manifestwork resource before it is applied.
type MutateManifestWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifestwork is the mutated manifestwork resource.
	Manifestwork  *runtime.Unknown `protobuf:"bytes,1,opt,name=manifestwork,proto3" json:"manifestwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateManifestWorkResponse) Reset() {
	*x = MutateManifestWorkResponse{}
	mi := &file_rollout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateManifestWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateManifestWorkResponse) ProtoMessage() {}

func (x *MutateManifestWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateManifestWorkResponse.ProtoReflect.Descriptor instead.
func (*MutateManifestWorkResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{9}
}

func (x *MutateManifestWorkResponse) GetManifestwork() *runtime.Unknown {
	if x != nil {
		return x.Manifestwork
	}
	return nil
}

type InitializeResponse_Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rollout is the capability to rollout.
	Rollout bool `protobuf:"varint,1,opt,name=rollout,proto3" json:"rollout,omitempty"`
	// rollback is the capability to rollback.
	Rollback bool `protobuf:"varint,2,opt,name=rollback,proto3" json:"rollback,omitempty"`
	// mutate_manifestwork is the capability to mutate the manifestwork resource.
	MutateManifestwork bool `protobuf:"varint,3,opt,name=mutate_manifestwork,json=mutateManifestwork,proto3" json:"mutate_manifestwork,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitializeResponse_Capabilities) Reset() {
	*x = InitializeResponse_Capabilities{}
	mi := &file_rollout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse_Capabilities) ProtoMessage() {}

func (x *InitializeResponse_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse_Capabilities.ProtoReflect.Descriptor instead.
func (*InitializeResponse_Capabilities) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitializeResponse_Capabilities) GetRollout() bool {
	if x != nil {
		return x.Rollout
	}
	return false
}

func (x *InitializeResponse_Capabilities) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

func (x *InitializeResponse_Capabilities) GetMutateManifestwork() bool {
	if x != nil {
		return x.MutateManifestwork
	}
	return false
}

var File_rollout_proto protoreflect.FileDescriptor

const file_rollout_proto_rawDesc = "" +
	"\n" +
	"\rrollout.proto\x124io.openclustermanagement.sdkgo.plugin.proto.v1alpha1\x1a\x19google/protobuf/any.proto\x1a/k8s.io/apimachinery/pkg/runtime/generated.proto\"4\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vocm_version\x18\x01 \x01(\tR\n" +
	"ocmVersion\"\xb4\x02\n" +
	"\x12InitializeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12y\n" +
	"\fcapabilities\x18\x03 \x01(\v2U.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse.CapabilitiesR\fcapabilities\x1au\n" +
	"\fCapabilities\x12\x18\n" +
	"\arollout\x18\x01 \x01(\bR\arollout\x12\x1a\n" +
	"\brollback\x18\x02 \x01(\bR\brollback\x12/\n" +
	"\x13mutate_manifestwork\x18\x03 \x01(\bR\x12mutateManifestwork\"Q\n" +
	"\x14ClusterRolloutStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0erollout_status\x18\x02 \x01(\tR\rrolloutStatus\"\xf0\x03\n" +
	"\x0eRolloutDetails\x12h\n" +
	"\tcompleted\x18\x01 \x03(\v2J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatusR\tcompleted\x12k\n" +
	"\vin_progress\x18\x02 \x03(\v2J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatusR\n" +
	"inProgress\x12g\n" +
	"\ttimed_out\x18\x03 \x03(\v2J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatusR\btimedOut\x12d\n" +
	"\aremoved\x18\x04 \x03(\v2J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatusR\aremoved\x128\n" +
	"\x18placement_total_clusters\x18\x06 \x01(\x05R\x16placementTotalClusters\"\xa8\x01\n" +
	"\vRolloutMeta\x12\x1b\n" +
	"\tmwrs_name\x18\x01 \x01(\tR\bmwrsName\x12%\n" +
	"\x0eplacement_name\x18\x02 \x01(\tR\rplacementName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12&\n" +
	"\fcluster_name\x18\x04 \x01(\tH\x00R\vclusterName\x88\x01\x01B\x0f\n" +
	"\r_cluster_name\"\xfd\x01\n" +
	"\x14RolloutPluginRequest\x12]\n" +
	"\bmetadata\x18\x01 \x01(\v2A.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutMetaR\bmetadata\x12r\n" +
	"\x0frollout_details\x18\a \x01(\v2D.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetailsH\x00R\x0erolloutDetails\x88\x01\x01B\x12\n" +
	"\x10_rollout_details\"\x97\x02\n" +
	"\x15RolloutPluginResponse\x12j\n" +
	"\x06result\x18\x01 \x01(\x0e2R.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse.ResultR\x06result\x12\x1d\n" +
	"\ttext_data\x18\x02 \x01(\tH\x00R\btextData\x125\n" +
	"\n" +
	"proto_data\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\tprotoData\"4\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02B\x06\n" +
	"\x04data\"\xa4\x02\n" +
	"\x10ValidateResponse\x12e\n" +
	"\x06result\x18\x01 \x01(\x0e2M.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse.ResultR\x06result\x12\x1d\n" +
	"\ttext_data\x18\x02 \x01(\tH\x00R\btextData\x125\n" +
	"\n" +
	"proto_data\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\tprotoData\"K\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUCCEEDED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\x0e\n" +
	"\n" +
	"INPROGRESS\x10\x03B\x06\n" +
	"\x04data\"\x9e\x04\n" +
	"\x19MutateManifestWorkRequest\x12\x81\x01\n" +
	"\rrollout_state\x18\x01 \x01(\x0e2\\.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.RolloutStateR\frolloutState\x12]\n" +
	"\bmetadata\x18\x02 \x01(\v2A.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutMetaR\bmetadata\x12r\n" +
	"\x0frollout_details\x18\x03 \x01(\v2D.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetailsH\x00R\x0erolloutDetails\x88\x01\x01\x12L\n" +
	"\fmanifestwork\x18\x04 \x01(\v2(.k8s.io.apimachinery.pkg.runtime.UnknownR\fmanifestwork\"H\n" +
	"\fRolloutState\x12\x1d\n" +
	"\x19ROLLOUT_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aROLLOUT\x10\x01\x12\f\n" +
	"\bROLLBACK\x10\x02B\x12\n" +
	"\x10_rollout_details\"j\n" +
	"\x1aMutateManifestWorkResponse\x12L\n" +
	"\fmanifestwork\x18\x01 \x01(\v2(.k8s.io.apimachinery.pkg.runtime.UnknownR\fmanifestwork2\xf3\n" +
	"\n" +
	"\x14RolloutPluginService\x12\x9f\x01\n" +
	"\n" +
	"Initialize\x12G.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeRequest\x1aH.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse\x12\xa7\x01\n" +
	"\fBeginRollout\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aK.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse\x12\xaa\x01\n" +
	"\x0fProgressRollout\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aK.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse\x12\xa5\x01\n" +
	"\x0fValidateRollout\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aF.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse\x12\xa8\x01\n" +
	"\rBeginRollback\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aK.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse\x12\xab\x01\n" +
	"\x10ProgressRollback\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aK.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse\x12\xa6\x01\n" +
	"\x10ValidateRollback\x12J.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest\x1aF.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse\x12\xb7\x01\n" +
	"\x12MutateManifestWork\x12O.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest\x1aP.io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkResponseBBZ@open-cluster-management.io/sdk-go/plugin/proto/v1alpha1;v1alpha1b\x06proto3"

var (
	file_rollout_proto_rawDescOnce sync.Once
	file_rollout_proto_rawDescData []byte
)

func file_rollout_proto_rawDescGZIP() []byte {
	file_rollout_proto_rawDescOnce.Do(func() {
		file_rollout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollout_proto_rawDesc), len(file_rollout_proto_rawDesc)))
	})
	return file_rollout_proto_rawDescData
}

var file_rollout_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rollout_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rollout_proto_goTypes = []any{
	(RolloutPluginResponse_Result)(0),           // 0: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse.Result
	(ValidateResponse_Result)(0),                // 1: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse.Result
	(MutateManifestWorkRequest_RolloutState)(0), // 2: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.RolloutState
	(*InitializeRequest)(nil),                   // 3: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeRequest
	(*InitializeResponse)(nil),                  // 4: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse
	(*ClusterRolloutStatus)(nil),                // 5: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatus
	(*RolloutDetails)(nil),                      // 6: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails
	(*RolloutMeta)(nil),                         // 7: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutMeta
	(*RolloutPluginRequest)(nil),                // 8: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	(*RolloutPluginResponse)(nil),               // 9: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse
	(*ValidateResponse)(nil),                    // 10: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse
	(*MutateManifestWorkRequest)(nil),           // 11: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest
	(*MutateManifestWorkResponse)(nil),          // 12: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkResponse
	(*InitializeResponse_Capabilities)(nil),     // 13: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse.Capabilities
	(*anypb.Any)(nil),                           // 14: google.protobuf.Any
	(*runtime.Unknown)(nil),                     // 15: k8s.io.apimachinery.pkg.runtime.Unknown
}
var file_rollout_proto_depIdxs = []int32{
	13, // 0: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse.capabilities:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse.Capabilities
	5,  // 1: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails.completed:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatus
	5,  // 2: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails.in_progress:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatus
	5,  // 3: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails.timed_out:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatus
	5,  // 4: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails.removed:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ClusterRolloutStatus
	7,  // 5: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest.metadata:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutMeta
	6,  // 6: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest.rollout_details:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails
	0,  // 7: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse.result:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse.Result
	14, // 8: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse.proto_data:type_name -> google.protobuf.Any
	1,  // 9: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse.result:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse.Result
	14, // 10: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse.proto_data:type_name -> google.protobuf.Any
	2,  // 11: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.rollout_state:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.RolloutState
	7,  // 12: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.metadata:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutMeta
	6,  // 13: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.rollout_details:type_name -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutDetails
	15, // 14: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest.manifestwork:type_name -> k8s.io.apimachinery.pkg.runtime.Unknown
	15, // 15: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkResponse.manifestwork:type_name -> k8s.io.apimachinery.pkg.runtime.Unknown
	3,  // 16: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.Initialize:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeRequest
	8,  // 17: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.BeginRollout:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	8,  // 18: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ProgressRollout:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	8,  // 19: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ValidateRollout:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	8,  // 20: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.BeginRollback:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	8,  // 21: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ProgressRollback:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	8,  // 22: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ValidateRollback:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginRequest
	11, // 23: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.MutateManifestWork:input_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkRequest
	4,  // 24: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.Initialize:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.InitializeResponse
	9,  // 25: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.BeginRollout:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse
	9,  // 26: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ProgressRollout:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse
	10, // 27: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ValidateRollout:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse
	9,  // 28: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.BeginRollback:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse
	9,  // 29: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ProgressRollback:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginResponse
	10, // 30: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.ValidateRollback:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.ValidateResponse
	12, // 31: io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.RolloutPluginService.MutateManifestWork:output_type -> io.openclustermanagement.sdkgo.plugin.proto.v1alpha1.MutateManifestWorkResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_rollout_proto_init() }
func file_rollout_proto_init() {
	if File_rollout_proto != nil {
		return
	}
	file_rollout_proto_msgTypes[4].OneofWrappers = []any{}
	file_rollout_proto_msgTypes[5].OneofWrappers = []any{}
	file_rollout_proto_msgTypes[6].OneofWrappers = []any{
		(*RolloutPluginResponse_TextData)(nil),
		(*RolloutPluginResponse_ProtoData)(nil),
	}
	file_rollout_proto_msgTypes[7].OneofWrappers = []any{
		(*ValidateResponse_TextData)(nil),
		(*ValidateResponse_ProtoData)(nil),
	}
	file_rollout_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollout_proto_rawDesc), len(file_rollout_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollout_proto_goTypes,
		DependencyIndexes: file_rollout_proto_depIdxs,
		EnumInfos:         file_rollout_proto_enumTypes,
		MessageInfos:      file_rollout_proto_msgTypes,
	}.Build()
	File_rollout_proto = out.File
	file_rollout_proto_goTypes = nil
	file_rollout_proto_depIdxs = nil
}
