// After making changes to the *.proto files, always run the following
// command in current directory to update the generated code:
// go generate

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rollout.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Result is the result of the plugin response.
type RolloutPluginResponse_Result int32

const (
	RolloutPluginResponse_RESULT_UNSPECIFIED RolloutPluginResponse_Result = 0
	// OK is the ok response.
	RolloutPluginResponse_OK RolloutPluginResponse_Result = 1
	// FAILED is the failed response.
	RolloutPluginResponse_FAILED RolloutPluginResponse_Result = 2
)

// Enum value maps for RolloutPluginResponse_Result.
var (
	RolloutPluginResponse_Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "OK",
		2: "FAILED",
	}
	RolloutPluginResponse_Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"OK":                 1,
		"FAILED":             2,
	}
)

func (x RolloutPluginResponse_Result) Enum() *RolloutPluginResponse_Result {
	p := new(RolloutPluginResponse_Result)
	*p = x
	return p
}

func (x RolloutPluginResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RolloutPluginResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[0].Descriptor()
}

func (RolloutPluginResponse_Result) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[0]
}

func (x RolloutPluginResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RolloutPluginResponse_Result.Descriptor instead.
func (RolloutPluginResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{6, 0}
}

// Result is the result of the validation response.
type ValidateRolloutResponse_Result int32

const (
	// RESULT_UNSPECIFIED is the unspecified result.
	ValidateRolloutResponse_RESULT_UNSPECIFIED ValidateRolloutResponse_Result = 0
	// SUCCEEDED represents the successful result of the validation.
	// MWRS Controller continues the rollout to the next group of clusters.
	ValidateRolloutResponse_SUCCEEDED ValidateRolloutResponse_Result = 1
	// FAILED represents the failed result of the validation.
	// MWRS Controller stops the current rollout and rollback is triggered if the rollback is required.
	ValidateRolloutResponse_FAILED ValidateRolloutResponse_Result = 2
	// INPROGRESS represents the state where the validation is still in progress.
	// MWRS Controller keeps calling this method until the result is not INPROGRESS.
	ValidateRolloutResponse_INPROGRESS ValidateRolloutResponse_Result = 3
)

// Enum value maps for ValidateRolloutResponse_Result.
var (
	ValidateRolloutResponse_Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "SUCCEEDED",
		2: "FAILED",
		3: "INPROGRESS",
	}
	ValidateRolloutResponse_Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"SUCCEEDED":          1,
		"FAILED":             2,
		"INPROGRESS":         3,
	}
)

func (x ValidateRolloutResponse_Result) Enum() *ValidateRolloutResponse_Result {
	p := new(ValidateRolloutResponse_Result)
	*p = x
	return p
}

func (x ValidateRolloutResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateRolloutResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[1].Descriptor()
}

func (ValidateRolloutResponse_Result) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[1]
}

func (x ValidateRolloutResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateRolloutResponse_Result.Descriptor instead.
func (ValidateRolloutResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{7, 0}
}

type MutateManifestWorkRequest_Type int32

const (
	MutateManifestWorkRequest_TYPE_UNSPECIFIED MutateManifestWorkRequest_Type = 0
	// ROLLOUT is the type of the mutation for the rollout.
	MutateManifestWorkRequest_ROLLOUT MutateManifestWorkRequest_Type = 1
	// ROLLBACK is the type of the mutation for the rollback.
	MutateManifestWorkRequest_ROLLBACK MutateManifestWorkRequest_Type = 2
)

// Enum value maps for MutateManifestWorkRequest_Type.
var (
	MutateManifestWorkRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "ROLLOUT",
		2: "ROLLBACK",
	}
	MutateManifestWorkRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"ROLLOUT":          1,
		"ROLLBACK":         2,
	}
)

func (x MutateManifestWorkRequest_Type) Enum() *MutateManifestWorkRequest_Type {
	p := new(MutateManifestWorkRequest_Type)
	*p = x
	return p
}

func (x MutateManifestWorkRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutateManifestWorkRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_rollout_proto_enumTypes[2].Descriptor()
}

func (MutateManifestWorkRequest_Type) Type() protoreflect.EnumType {
	return &file_rollout_proto_enumTypes[2]
}

func (x MutateManifestWorkRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutateManifestWorkRequest_Type.Descriptor instead.
func (MutateManifestWorkRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{8, 0}
}

// InitPluginRequest is the request to initialize the plugin.
type InitPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ocm_version is the version of the OCM API.
	OcmVersion    string `protobuf:"bytes,1,opt,name=ocm_version,json=ocmVersion,proto3" json:"ocm_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitPluginRequest) Reset() {
	*x = InitPluginRequest{}
	mi := &file_rollout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPluginRequest) ProtoMessage() {}

func (x *InitPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPluginRequest.ProtoReflect.Descriptor instead.
func (*InitPluginRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{0}
}

func (x *InitPluginRequest) GetOcmVersion() string {
	if x != nil {
		return x.OcmVersion
	}
	return ""
}

// InitPluginResponse is the response from the plugin after initialization.
// The plugin returns the name, version, and capabilities of the plugin.
type InitPluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the plugin.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the version of the plugin.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// capabilities is the capabilities of the plugin.
	Capabilities  *InitPluginResponse_Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitPluginResponse) Reset() {
	*x = InitPluginResponse{}
	mi := &file_rollout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPluginResponse) ProtoMessage() {}

func (x *InitPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPluginResponse.ProtoReflect.Descriptor instead.
func (*InitPluginResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{1}
}

func (x *InitPluginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitPluginResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitPluginResponse) GetCapabilities() *InitPluginResponse_Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ClusterRolloutStatus is the status of the cluster rollout.
type ClusterRolloutStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rollout_status is the status of the cluster rollout.
	RolloutStatus string `protobuf:"bytes,2,opt,name=rollout_status,json=rolloutStatus,proto3" json:"rollout_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRolloutStatus) Reset() {
	*x = ClusterRolloutStatus{}
	mi := &file_rollout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRolloutStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRolloutStatus) ProtoMessage() {}

func (x *ClusterRolloutStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRolloutStatus.ProtoReflect.Descriptor instead.
func (*ClusterRolloutStatus) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterRolloutStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterRolloutStatus) GetRolloutStatus() string {
	if x != nil {
		return x.RolloutStatus
	}
	return ""
}

// RolloutDetails is the details of the rollout.
type RolloutDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// completed is the clusters that have been completed.
	Completed []*ClusterRolloutStatus `protobuf:"bytes,1,rep,name=completed,proto3" json:"completed,omitempty"`
	// in_progress is the clusters that are currently being rolled out.
	InProgress []*ClusterRolloutStatus `protobuf:"bytes,2,rep,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	// timed_out is the clusters that have timed out.
	TimedOut []*ClusterRolloutStatus `protobuf:"bytes,3,rep,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// removed is the clusters that have been removed.
	Removed []*ClusterRolloutStatus `protobuf:"bytes,4,rep,name=removed,proto3" json:"removed,omitempty"`
	// placement_total_clusters is the total clusters in placement decision.
	PlacementTotalClusters int32 `protobuf:"varint,6,opt,name=placement_total_clusters,json=placementTotalClusters,proto3" json:"placement_total_clusters,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RolloutDetails) Reset() {
	*x = RolloutDetails{}
	mi := &file_rollout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutDetails) ProtoMessage() {}

func (x *RolloutDetails) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutDetails.ProtoReflect.Descriptor instead.
func (*RolloutDetails) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{3}
}

func (x *RolloutDetails) GetCompleted() []*ClusterRolloutStatus {
	if x != nil {
		return x.Completed
	}
	return nil
}

func (x *RolloutDetails) GetInProgress() []*ClusterRolloutStatus {
	if x != nil {
		return x.InProgress
	}
	return nil
}

func (x *RolloutDetails) GetTimedOut() []*ClusterRolloutStatus {
	if x != nil {
		return x.TimedOut
	}
	return nil
}

func (x *RolloutDetails) GetRemoved() []*ClusterRolloutStatus {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *RolloutDetails) GetPlacementTotalClusters() int32 {
	if x != nil {
		return x.PlacementTotalClusters
	}
	return 0
}

type RolloutMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mwrs_name is the name of the manifestwork resource set.
	MwrsName string `protobuf:"bytes,1,opt,name=mwrs_name,json=mwrsName,proto3" json:"mwrs_name,omitempty"`
	// placement_name is the name of the placement.
	PlacementName string `protobuf:"bytes,2,opt,name=placement_name,json=placementName,proto3" json:"placement_name,omitempty"`
	// namespace is the namespace where mwrs and placement are located.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// cluster_name is the name of the cluster.
	ClusterName   *string `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3,oneof" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutMeta) Reset() {
	*x = RolloutMeta{}
	mi := &file_rollout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutMeta) ProtoMessage() {}

func (x *RolloutMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutMeta.ProtoReflect.Descriptor instead.
func (*RolloutMeta) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{4}
}

func (x *RolloutMeta) GetMwrsName() string {
	if x != nil {
		return x.MwrsName
	}
	return ""
}

func (x *RolloutMeta) GetPlacementName() string {
	if x != nil {
		return x.PlacementName
	}
	return ""
}

func (x *RolloutMeta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RolloutMeta) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

// RolloutPluginRequest is the request to the rollout plugin.
type RolloutPluginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata is the metadata of the rollout.
	Metadata *RolloutMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// rollout_details is the details of the rollout.
	RolloutDetails *RolloutDetails `protobuf:"bytes,7,opt,name=rollout_details,json=rolloutDetails,proto3,oneof" json:"rollout_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RolloutPluginRequest) Reset() {
	*x = RolloutPluginRequest{}
	mi := &file_rollout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPluginRequest) ProtoMessage() {}

func (x *RolloutPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPluginRequest.ProtoReflect.Descriptor instead.
func (*RolloutPluginRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{5}
}

func (x *RolloutPluginRequest) GetMetadata() *RolloutMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RolloutPluginRequest) GetRolloutDetails() *RolloutDetails {
	if x != nil {
		return x.RolloutDetails
	}
	return nil
}

// RolloutPluginResponse is the response from the plugin.
type RolloutPluginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the result of the response.
	Result RolloutPluginResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse_Result" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*RolloutPluginResponse_TextData
	//	*RolloutPluginResponse_ProtoData
	Data          isRolloutPluginResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolloutPluginResponse) Reset() {
	*x = RolloutPluginResponse{}
	mi := &file_rollout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolloutPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolloutPluginResponse) ProtoMessage() {}

func (x *RolloutPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolloutPluginResponse.ProtoReflect.Descriptor instead.
func (*RolloutPluginResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{6}
}

func (x *RolloutPluginResponse) GetResult() RolloutPluginResponse_Result {
	if x != nil {
		return x.Result
	}
	return RolloutPluginResponse_RESULT_UNSPECIFIED
}

func (x *RolloutPluginResponse) GetData() isRolloutPluginResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RolloutPluginResponse) GetTextData() string {
	if x != nil {
		if x, ok := x.Data.(*RolloutPluginResponse_TextData); ok {
			return x.TextData
		}
	}
	return ""
}

func (x *RolloutPluginResponse) GetProtoData() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*RolloutPluginResponse_ProtoData); ok {
			return x.ProtoData
		}
	}
	return nil
}

type isRolloutPluginResponse_Data interface {
	isRolloutPluginResponse_Data()
}

type RolloutPluginResponse_TextData struct {
	// text_data is the text data of the response.
	TextData string `protobuf:"bytes,2,opt,name=text_data,json=textData,proto3,oneof"`
}

type RolloutPluginResponse_ProtoData struct {
	// proto_data is the protobuf data of the response.
	ProtoData *anypb.Any `protobuf:"bytes,3,opt,name=proto_data,json=protoData,proto3,oneof"`
}

func (*RolloutPluginResponse_TextData) isRolloutPluginResponse_Data() {}

func (*RolloutPluginResponse_ProtoData) isRolloutPluginResponse_Data() {}

// ValidateRolloutResponse is the response from the plugin for the validation of the rollout.
type ValidateRolloutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the result of the response.
	Result ValidateRolloutResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse_Result" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*ValidateRolloutResponse_TextData
	//	*ValidateRolloutResponse_ProtoData
	Data          isValidateRolloutResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRolloutResponse) Reset() {
	*x = ValidateRolloutResponse{}
	mi := &file_rollout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRolloutResponse) ProtoMessage() {}

func (x *ValidateRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRolloutResponse.ProtoReflect.Descriptor instead.
func (*ValidateRolloutResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRolloutResponse) GetResult() ValidateRolloutResponse_Result {
	if x != nil {
		return x.Result
	}
	return ValidateRolloutResponse_RESULT_UNSPECIFIED
}

func (x *ValidateRolloutResponse) GetData() isValidateRolloutResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ValidateRolloutResponse) GetTextData() string {
	if x != nil {
		if x, ok := x.Data.(*ValidateRolloutResponse_TextData); ok {
			return x.TextData
		}
	}
	return ""
}

func (x *ValidateRolloutResponse) GetProtoData() *anypb.Any {
	if x != nil {
		if x, ok := x.Data.(*ValidateRolloutResponse_ProtoData); ok {
			return x.ProtoData
		}
	}
	return nil
}

type isValidateRolloutResponse_Data interface {
	isValidateRolloutResponse_Data()
}

type ValidateRolloutResponse_TextData struct {
	// text_data is the text data of the response.
	TextData string `protobuf:"bytes,2,opt,name=text_data,json=textData,proto3,oneof"`
}

type ValidateRolloutResponse_ProtoData struct {
	// proto_data is the protobuf data of the response.
	ProtoData *anypb.Any `protobuf:"bytes,3,opt,name=proto_data,json=protoData,proto3,oneof"`
}

func (*ValidateRolloutResponse_TextData) isValidateRolloutResponse_Data() {}

func (*ValidateRolloutResponse_ProtoData) isValidateRolloutResponse_Data() {}

// MutateManifestWorkRequest is the request to mutate the manifestwork resource before it is applied.
type MutateManifestWorkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the type of the mutation.
	Type MutateManifestWorkRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest_Type" json:"type,omitempty"`
	// metadata is the metadata of the rollout.
	Metadata *RolloutMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// rollout_details is the details of the rollout.
	RolloutDetails *RolloutDetails `protobuf:"bytes,3,opt,name=rollout_details,json=rolloutDetails,proto3,oneof" json:"rollout_details,omitempty"`
	// manifestwork is the unstructured manifestwork resource.
	Manifestwork  *RuntimeObject `protobuf:"bytes,4,opt,name=manifestwork,proto3" json:"manifestwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateManifestWorkRequest) Reset() {
	*x = MutateManifestWorkRequest{}
	mi := &file_rollout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateManifestWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateManifestWorkRequest) ProtoMessage() {}

func (x *MutateManifestWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateManifestWorkRequest.ProtoReflect.Descriptor instead.
func (*MutateManifestWorkRequest) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{8}
}

func (x *MutateManifestWorkRequest) GetType() MutateManifestWorkRequest_Type {
	if x != nil {
		return x.Type
	}
	return MutateManifestWorkRequest_TYPE_UNSPECIFIED
}

func (x *MutateManifestWorkRequest) GetMetadata() *RolloutMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MutateManifestWorkRequest) GetRolloutDetails() *RolloutDetails {
	if x != nil {
		return x.RolloutDetails
	}
	return nil
}

func (x *MutateManifestWorkRequest) GetManifestwork() *RuntimeObject {
	if x != nil {
		return x.Manifestwork
	}
	return nil
}

// MutateManifestWorkResponse is the response to mutate the manifestwork resource before it is applied.
type MutateManifestWorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifestwork is the mutated manifestwork resource.
	Manifestwork  *RuntimeObject `protobuf:"bytes,1,opt,name=manifestwork,proto3" json:"manifestwork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateManifestWorkResponse) Reset() {
	*x = MutateManifestWorkResponse{}
	mi := &file_rollout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateManifestWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateManifestWorkResponse) ProtoMessage() {}

func (x *MutateManifestWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateManifestWorkResponse.ProtoReflect.Descriptor instead.
func (*MutateManifestWorkResponse) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{9}
}

func (x *MutateManifestWorkResponse) GetManifestwork() *RuntimeObject {
	if x != nil {
		return x.Manifestwork
	}
	return nil
}

// TypeMeta is the type meta of the kubernetes runtime object.
type TypeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeMeta) Reset() {
	*x = TypeMeta{}
	mi := &file_rollout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeMeta) ProtoMessage() {}

func (x *TypeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeMeta.ProtoReflect.Descriptor instead.
func (*TypeMeta) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{10}
}

func (x *TypeMeta) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TypeMeta) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// RuntimeObject is the kubernetes runtime object.
type RuntimeObject struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TypeMeta *TypeMeta              `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3" json:"type_meta,omitempty"`
	// Raw will hold the complete serialized object which couldn't be matched
	// with a registered type. Most likely, nothing should be done with this
	// except for passing it through the system.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// ContentType  is serialization method used to serialize 'Raw'.
	// Unspecified means ContentTypeJSON.
	ContentType   string `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeObject) Reset() {
	*x = RuntimeObject{}
	mi := &file_rollout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeObject) ProtoMessage() {}

func (x *RuntimeObject) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeObject.ProtoReflect.Descriptor instead.
func (*RuntimeObject) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeObject) GetTypeMeta() *TypeMeta {
	if x != nil {
		return x.TypeMeta
	}
	return nil
}

func (x *RuntimeObject) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *RuntimeObject) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type InitPluginResponse_Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rollout is the capability to rollout.
	Rollout bool `protobuf:"varint,1,opt,name=rollout,proto3" json:"rollout,omitempty"`
	// rollback is the capability to rollback.
	Rollback bool `protobuf:"varint,2,opt,name=rollback,proto3" json:"rollback,omitempty"`
	// mutate_manifestwork is the capability to mutate the manifestwork resource.
	MutateManifestwork bool `protobuf:"varint,3,opt,name=mutate_manifestwork,json=mutateManifestwork,proto3" json:"mutate_manifestwork,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitPluginResponse_Capabilities) Reset() {
	*x = InitPluginResponse_Capabilities{}
	mi := &file_rollout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPluginResponse_Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPluginResponse_Capabilities) ProtoMessage() {}

func (x *InitPluginResponse_Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_rollout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPluginResponse_Capabilities.ProtoReflect.Descriptor instead.
func (*InitPluginResponse_Capabilities) Descriptor() ([]byte, []int) {
	return file_rollout_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitPluginResponse_Capabilities) GetRollout() bool {
	if x != nil {
		return x.Rollout
	}
	return false
}

func (x *InitPluginResponse_Capabilities) GetRollback() bool {
	if x != nil {
		return x.Rollback
	}
	return false
}

func (x *InitPluginResponse_Capabilities) GetMutateManifestwork() bool {
	if x != nil {
		return x.MutateManifestwork
	}
	return false
}

var File_rollout_proto protoreflect.FileDescriptor

const file_rollout_proto_rawDesc = "" +
	"\n" +
	"\rrollout.proto\x12%io.openclustermanagement.sdkgo.plugin\x1a\x19google/protobuf/any.proto\"4\n" +
	"\x11InitPluginRequest\x12\x1f\n" +
	"\vocm_version\x18\x01 \x01(\tR\n" +
	"ocmVersion\"\xa5\x02\n" +
	"\x12InitPluginResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12j\n" +
	"\fcapabilities\x18\x03 \x01(\v2F.io.openclustermanagement.sdkgo.plugin.InitPluginResponse.CapabilitiesR\fcapabilities\x1au\n" +
	"\fCapabilities\x12\x18\n" +
	"\arollout\x18\x01 \x01(\bR\arollout\x12\x1a\n" +
	"\brollback\x18\x02 \x01(\bR\brollback\x12/\n" +
	"\x13mutate_manifestwork\x18\x03 \x01(\bR\x12mutateManifestwork\"Q\n" +
	"\x14ClusterRolloutStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0erollout_status\x18\x02 \x01(\tR\rrolloutStatus\"\xb4\x03\n" +
	"\x0eRolloutDetails\x12Y\n" +
	"\tcompleted\x18\x01 \x03(\v2;.io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatusR\tcompleted\x12\\\n" +
	"\vin_progress\x18\x02 \x03(\v2;.io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatusR\n" +
	"inProgress\x12X\n" +
	"\ttimed_out\x18\x03 \x03(\v2;.io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatusR\btimedOut\x12U\n" +
	"\aremoved\x18\x04 \x03(\v2;.io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatusR\aremoved\x128\n" +
	"\x18placement_total_clusters\x18\x06 \x01(\x05R\x16placementTotalClusters\"\xa8\x01\n" +
	"\vRolloutMeta\x12\x1b\n" +
	"\tmwrs_name\x18\x01 \x01(\tR\bmwrsName\x12%\n" +
	"\x0eplacement_name\x18\x02 \x01(\tR\rplacementName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12&\n" +
	"\fcluster_name\x18\x04 \x01(\tH\x00R\vclusterName\x88\x01\x01B\x0f\n" +
	"\r_cluster_name\"\xdf\x01\n" +
	"\x14RolloutPluginRequest\x12N\n" +
	"\bmetadata\x18\x01 \x01(\v22.io.openclustermanagement.sdkgo.plugin.RolloutMetaR\bmetadata\x12c\n" +
	"\x0frollout_details\x18\a \x01(\v25.io.openclustermanagement.sdkgo.plugin.RolloutDetailsH\x00R\x0erolloutDetails\x88\x01\x01B\x12\n" +
	"\x10_rollout_details\"\x88\x02\n" +
	"\x15RolloutPluginResponse\x12[\n" +
	"\x06result\x18\x01 \x01(\x0e2C.io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse.ResultR\x06result\x12\x1d\n" +
	"\ttext_data\x18\x02 \x01(\tH\x00R\btextData\x125\n" +
	"\n" +
	"proto_data\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\tprotoData\"4\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02B\x06\n" +
	"\x04data\"\xa3\x02\n" +
	"\x17ValidateRolloutResponse\x12]\n" +
	"\x06result\x18\x01 \x01(\x0e2E.io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse.ResultR\x06result\x12\x1d\n" +
	"\ttext_data\x18\x02 \x01(\tH\x00R\btextData\x125\n" +
	"\n" +
	"proto_data\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\tprotoData\"K\n" +
	"\x06Result\x12\x16\n" +
	"\x12RESULT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUCCEEDED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\x0e\n" +
	"\n" +
	"INPROGRESS\x10\x03B\x06\n" +
	"\x04data\"\xd2\x03\n" +
	"\x19MutateManifestWorkRequest\x12Y\n" +
	"\x04type\x18\x01 \x01(\x0e2E.io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.TypeR\x04type\x12N\n" +
	"\bmetadata\x18\x02 \x01(\v22.io.openclustermanagement.sdkgo.plugin.RolloutMetaR\bmetadata\x12c\n" +
	"\x0frollout_details\x18\x03 \x01(\v25.io.openclustermanagement.sdkgo.plugin.RolloutDetailsH\x00R\x0erolloutDetails\x88\x01\x01\x12X\n" +
	"\fmanifestwork\x18\x04 \x01(\v24.io.openclustermanagement.sdkgo.plugin.RuntimeObjectR\fmanifestwork\"7\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aROLLOUT\x10\x01\x12\f\n" +
	"\bROLLBACK\x10\x02B\x12\n" +
	"\x10_rollout_details\"v\n" +
	"\x1aMutateManifestWorkResponse\x12X\n" +
	"\fmanifestwork\x18\x01 \x01(\v24.io.openclustermanagement.sdkgo.plugin.RuntimeObjectR\fmanifestwork\"?\n" +
	"\bTypeMeta\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\x91\x01\n" +
	"\rRuntimeObject\x12L\n" +
	"\ttype_meta\x18\x01 \x01(\v2/.io.openclustermanagement.sdkgo.plugin.TypeMetaR\btypeMeta\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12 \n" +
	"\vcontentType\x18\x03 \x01(\tR\vcontentType2\x91\t\n" +
	"\x14RolloutPluginService\x12\x81\x01\n" +
	"\n" +
	"InitPlugin\x128.io.openclustermanagement.sdkgo.plugin.InitPluginRequest\x1a9.io.openclustermanagement.sdkgo.plugin.InitPluginResponse\x12\x89\x01\n" +
	"\fBeginRollout\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a<.io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse\x12\x8c\x01\n" +
	"\x0fProgressRollout\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a<.io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse\x12\x8e\x01\n" +
	"\x0fValidateRollout\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a>.io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse\x12\x8a\x01\n" +
	"\rBeginRollback\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a<.io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse\x12\x8d\x01\n" +
	"\x10ProgressRollback\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a<.io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse\x12\x8f\x01\n" +
	"\x10ValidateRollback\x12;.io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest\x1a>.io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse\x12\x99\x01\n" +
	"\x12MutateManifestWork\x12@.io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest\x1aA.io.openclustermanagement.sdkgo.plugin.MutateManifestWorkResponseB1Z/open-cluster-management.io/sdk-go/plugin;pluginb\x06proto3"

var (
	file_rollout_proto_rawDescOnce sync.Once
	file_rollout_proto_rawDescData []byte
)

func file_rollout_proto_rawDescGZIP() []byte {
	file_rollout_proto_rawDescOnce.Do(func() {
		file_rollout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rollout_proto_rawDesc), len(file_rollout_proto_rawDesc)))
	})
	return file_rollout_proto_rawDescData
}

var file_rollout_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rollout_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rollout_proto_goTypes = []any{
	(RolloutPluginResponse_Result)(0),       // 0: io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse.Result
	(ValidateRolloutResponse_Result)(0),     // 1: io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse.Result
	(MutateManifestWorkRequest_Type)(0),     // 2: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.Type
	(*InitPluginRequest)(nil),               // 3: io.openclustermanagement.sdkgo.plugin.InitPluginRequest
	(*InitPluginResponse)(nil),              // 4: io.openclustermanagement.sdkgo.plugin.InitPluginResponse
	(*ClusterRolloutStatus)(nil),            // 5: io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatus
	(*RolloutDetails)(nil),                  // 6: io.openclustermanagement.sdkgo.plugin.RolloutDetails
	(*RolloutMeta)(nil),                     // 7: io.openclustermanagement.sdkgo.plugin.RolloutMeta
	(*RolloutPluginRequest)(nil),            // 8: io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	(*RolloutPluginResponse)(nil),           // 9: io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse
	(*ValidateRolloutResponse)(nil),         // 10: io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse
	(*MutateManifestWorkRequest)(nil),       // 11: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest
	(*MutateManifestWorkResponse)(nil),      // 12: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkResponse
	(*TypeMeta)(nil),                        // 13: io.openclustermanagement.sdkgo.plugin.TypeMeta
	(*RuntimeObject)(nil),                   // 14: io.openclustermanagement.sdkgo.plugin.RuntimeObject
	(*InitPluginResponse_Capabilities)(nil), // 15: io.openclustermanagement.sdkgo.plugin.InitPluginResponse.Capabilities
	(*anypb.Any)(nil),                       // 16: google.protobuf.Any
}
var file_rollout_proto_depIdxs = []int32{
	15, // 0: io.openclustermanagement.sdkgo.plugin.InitPluginResponse.capabilities:type_name -> io.openclustermanagement.sdkgo.plugin.InitPluginResponse.Capabilities
	5,  // 1: io.openclustermanagement.sdkgo.plugin.RolloutDetails.completed:type_name -> io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatus
	5,  // 2: io.openclustermanagement.sdkgo.plugin.RolloutDetails.in_progress:type_name -> io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatus
	5,  // 3: io.openclustermanagement.sdkgo.plugin.RolloutDetails.timed_out:type_name -> io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatus
	5,  // 4: io.openclustermanagement.sdkgo.plugin.RolloutDetails.removed:type_name -> io.openclustermanagement.sdkgo.plugin.ClusterRolloutStatus
	7,  // 5: io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest.metadata:type_name -> io.openclustermanagement.sdkgo.plugin.RolloutMeta
	6,  // 6: io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest.rollout_details:type_name -> io.openclustermanagement.sdkgo.plugin.RolloutDetails
	0,  // 7: io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse.result:type_name -> io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse.Result
	16, // 8: io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse.proto_data:type_name -> google.protobuf.Any
	1,  // 9: io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse.result:type_name -> io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse.Result
	16, // 10: io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse.proto_data:type_name -> google.protobuf.Any
	2,  // 11: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.type:type_name -> io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.Type
	7,  // 12: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.metadata:type_name -> io.openclustermanagement.sdkgo.plugin.RolloutMeta
	6,  // 13: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.rollout_details:type_name -> io.openclustermanagement.sdkgo.plugin.RolloutDetails
	14, // 14: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest.manifestwork:type_name -> io.openclustermanagement.sdkgo.plugin.RuntimeObject
	14, // 15: io.openclustermanagement.sdkgo.plugin.MutateManifestWorkResponse.manifestwork:type_name -> io.openclustermanagement.sdkgo.plugin.RuntimeObject
	13, // 16: io.openclustermanagement.sdkgo.plugin.RuntimeObject.type_meta:type_name -> io.openclustermanagement.sdkgo.plugin.TypeMeta
	3,  // 17: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.InitPlugin:input_type -> io.openclustermanagement.sdkgo.plugin.InitPluginRequest
	8,  // 18: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.BeginRollout:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	8,  // 19: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ProgressRollout:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	8,  // 20: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ValidateRollout:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	8,  // 21: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.BeginRollback:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	8,  // 22: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ProgressRollback:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	8,  // 23: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ValidateRollback:input_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginRequest
	11, // 24: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.MutateManifestWork:input_type -> io.openclustermanagement.sdkgo.plugin.MutateManifestWorkRequest
	4,  // 25: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.InitPlugin:output_type -> io.openclustermanagement.sdkgo.plugin.InitPluginResponse
	9,  // 26: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.BeginRollout:output_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse
	9,  // 27: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ProgressRollout:output_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse
	10, // 28: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ValidateRollout:output_type -> io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse
	9,  // 29: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.BeginRollback:output_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse
	9,  // 30: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ProgressRollback:output_type -> io.openclustermanagement.sdkgo.plugin.RolloutPluginResponse
	10, // 31: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.ValidateRollback:output_type -> io.openclustermanagement.sdkgo.plugin.ValidateRolloutResponse
	12, // 32: io.openclustermanagement.sdkgo.plugin.RolloutPluginService.MutateManifestWork:output_type -> io.openclustermanagement.sdkgo.plugin.MutateManifestWorkResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rollout_proto_init() }
func file_rollout_proto_init() {
	if File_rollout_proto != nil {
		return
	}
	file_rollout_proto_msgTypes[4].OneofWrappers = []any{}
	file_rollout_proto_msgTypes[5].OneofWrappers = []any{}
	file_rollout_proto_msgTypes[6].OneofWrappers = []any{
		(*RolloutPluginResponse_TextData)(nil),
		(*RolloutPluginResponse_ProtoData)(nil),
	}
	file_rollout_proto_msgTypes[7].OneofWrappers = []any{
		(*ValidateRolloutResponse_TextData)(nil),
		(*ValidateRolloutResponse_ProtoData)(nil),
	}
	file_rollout_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rollout_proto_rawDesc), len(file_rollout_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rollout_proto_goTypes,
		DependencyIndexes: file_rollout_proto_depIdxs,
		EnumInfos:         file_rollout_proto_enumTypes,
		MessageInfos:      file_rollout_proto_msgTypes,
	}.Build()
	File_rollout_proto = out.File
	file_rollout_proto_goTypes = nil
	file_rollout_proto_depIdxs = nil
}
